language: python
python:
    - "2.7"
sudo: false
cache:
    directories:
        - "~/.platformio"
env:
    - PLATFORMIO_CI_SRC=examples/decoder PLATFORMIO_CI_EXTRA_ARGS="--project-option=lib_deps=APRS-Decoder-Lib"
    - PLATFORMIO_CI_SRC=examples/simple_aprs
    - PLATFORMIO_CI_SRC=examples/simple_fixed_position PLATFORMIO_CI_EXTRA_ARGS="--project-option=lib_deps=NTPClient"
install:
    - pip install -U platformio
    - platformio update
script:
    - platformio ci --lib="." --board=ttgo-lora32-v1 --board=d1_mini $PLATFORMIO_CI_EXTRA_ARGS
