name: Build check and build

on: [push, pull_request]

jobs:
  PlatformIO-Check:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: pip3 install platformio
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - run: platformio check --fail-on-defect low --fail-on-defect medium --fail-on-defect high

  PlatformIO-Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/decoder, examples/simple_aprs, examples/simple_fixed_position]
    steps:
      - run: sudo apt-get install python3-setuptools python3-wheel
      - run: pip3 install platformio
      - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
      - name: Run PlatformIO
        run: platformio ci --lib="." -c ci_platformio.ini
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}

